global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - send_resolved: true